# Generated by Django 3.2.6 on 2021-08-16 03:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limits', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=7)),
                ('healthScore', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=5)),
                ('controlLimitType', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
