# Generated by Django 3.2.6 on 2021-08-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataValues',
            new_name='DataValue',
        ),
        migrations.AlterField(
            model_name='meter',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
