# Generated by Django 3.2.6 on 2021-11-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_excelfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excelfiles',
            name='file_data',
        ),
    ]
