# Generated by Django 3.2.6 on 2022-02-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_remove_excelfiles_file_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
